AWSTemplateFormatVersion: '2010-09-09'
Description: 'Architecture sécurisée avec ALB, Auto Scaling et RDS multi-AZ'

Parameters:
  KeyName:
    Description: 'Nom de la paire de clés EC2 existante'
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: 'Doit être le nom d\'une paire de clés EC2 existante'

Resources:
  # VPC avec NAT Gateway pour l'isolation
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: 'SecureApp-VPC'

  # ALB avec sécurité renforcée
  ApplicationLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: 'true'
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'true'
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup

  # Auto Scaling Group avec politique de scaling
  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: '2'
      MaxSize: '4'
      DesiredCapacity: '2'
      TargetGroupARNs:
        - !Ref TargetGroup
      VPCZoneIdentifier: !Ref PrivateSubnets

Outputs:
  ALBDNSName:
    Description: 'URL d\'accès à l\'application'
    Value: !GetAtt ApplicationLoadBalancer.DNSName